version: "3"
services:
    rest-fights:
        image: quarkus/rest-fights-jvm
        container_name: "rest-fights"
        mem_limit: 128m
        environment:
            - QUARKUS_DATASOURCE_URL=jdbc:postgresql://quarkus-db:5432/fights_database
        ports:
            - "8082:8082"  # the HTTP endpoint
        depends_on:
            quarkus-db:
                condition: service_healthy
        networks:
            - quarkus

    quarkus-db:
        image: "postgres:13.4"
        mem_limit: 128m
        environment:
            - POSTGRES_PASSWORD=superfight
        volumes:
            - ./src/main/resources/db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U superfight -d fights_database"]
            interval: 5s
            timeout: 5s
            retries: 6
        ports:
            - "5437:5432"
        networks:
            - quarkus

networks:
    quarkus:
        driver: bridge
