version: "3"
services:
    rest-heroes:
        image: quarkus/rest-heroes-jvm
        container_name: "rest-heroes"
        mem_limit: 128m
        environment:
            - QUARKUS_DATASOURCE_URL=jdbc:postgresql://quarkus-db:5432/heroes_database
        ports:
            - "8083:8083"  # the HTTP endpoint
        depends_on:
            quarkus-db:
                condition: service_healthy
        networks:
            - quarkus

    quarkus-db:
        image: "postgres:13.4"
        mem_limit: 128m
        volumes:
            - ./src/main/resources/db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U superman -d heroes_database"]
            interval: 5s
            timeout: 5s
            retries: 6
        ports:
            - "5438:5432"
        networks:
            - quarkus

networks:
    quarkus:
        driver: bridge
